var express = require('express');
var app = express();
var mongoose = require('mongoose');
var bodyParser = require('body-parser');
app.use(bodyParser.json());
app.use(express.static(__dirname + "/public/dist/public"));
mongoose.Promise = global.Promise;
require('./models/fan.js').fan();
require('./config/routes.js')(app);
app.listen(8000);